CREATE TABLE IF NOT EXISTS Beneficiario(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    telefone VARCHAR(255),
    data_nascimento DATE,
    data_inclusao DATE,
    data_atualizacao DATE
);

CREATE TABLE IF NOT EXISTS Documento(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento VARCHAR(255),
    descricao VARCHAR(255),
    data_inclusao DATE,
    data_atualizacao DATE,
    beneficiario_id BIGINT,
    constraint FK_beneficiario_documento foreign key(beneficiario_id) references Beneficiario(id)
);

